### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by luigi-palladino** [dhdhagar/byokg#1]
Hello, the article is very interesting, I would really like to try the implementation. Is there a timeline/date for the release?

**Comment by dhdhagar** [comment]
Hi! Glad you like our work! We're going through internal approvals before we can put the code out. Timelines are not 100%, but my estimate right now is within a month. Please stay tuned!

**Comment by Pzeyang** [comment]
Hello, the paper is great! I want to see the code, when will the code be released?

**Comment by dhdhagar** [comment]
Hi Zeyang, thanks for the interest! It will be released this month. Please continue to track this space.

**Comment by ri-git** [comment]
By when will the code be released? Additionally, could you please share your evaluation dataset based on MatKG? Thanks!

**Comment by dhdhagar** [comment]
Hi @ri-git, thanks for your interest in the work! We've unfortunately had delays in getting this out 😞 The good news is that the open-sourcing process is underway and it should be just a few days now 🤞🏼 I'll put an update on this thread once it's done!

As for the MatKG QA dataset, you can find that here: https://drive.google.com/file/d/1o8CG9isSOScTZ3Ji1-71EzBEZoZqvnCR/view?usp=drive_link.

**Comment by dhdhagar** [comment]
Hi @ri-git @Pzeyang @luigi-palladino, the code is now open-sourced at https://github.com/amazon-science/BYOKG-NAACL24.
